//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.Common.Examples.web.monoserver {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="monoserver.Itest2")]
    public interface Itest2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Itest2/DoWork", ReplyAction="http://tempuri.org/Itest2/DoWorkResponse")]
        string DoWork();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Itest2Channel : JM.Common.Examples.web.monoserver.Itest2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Itest2Client : System.ServiceModel.ClientBase<JM.Common.Examples.web.monoserver.Itest2>, JM.Common.Examples.web.monoserver.Itest2 {
        
        public Itest2Client() {
        }
        
        public Itest2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Itest2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Itest2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Itest2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
    }
}
